name: terminal
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          java-package: jdk
          architecture: x64
      - run: javac *.java; java Color; java Args 12345 < README.md;
        working-directory: terminal
